config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :user, only: %i[show create update destroy] do
    resources :permalinks, only: %i[index show create destroy]
    resources :queries, only: %i[index show create destroy]
  end

  resource :settings

  mount ActionCable.server => "/cable"

  get "search", to: "search#index"
  get "search/autocomplete", to: "search#autocomplete"

  root "home#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-primary <%= content_for(:page) == 'home' ? '' : 'mb-3' %>">
  <div class="container-fluid">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% unless content_for(:page) == 'home' %>
      <a class="navbar-brand fw-bold" href="/">Search</a>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% unless content_for(:page) == 'home' %>
        <%= render 'search/form' %>
      <% end %>

      <% if database_present? %>
        <div class="navbar-nav ml-auto">
            <%= link_to 'Settings', edit_settings_path, class: "nav-item nav-link pb-0 pr-0 ml-2 #{content_for(:page) == 'settings' ? 'active' : ''}" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for(:title) || 'News' %></title>
    <% if controller_name == 'search' && action_name == 'index' %>
      <%= auto_discovery_link_tag(:atom, search_url(format: :atom, q: params[:q]), title: content_for(:title)) %>
    <% end %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= content_for(:page) %>" class="d-flex flex-column" style="min-height:100vh">

    <% #unless content_for(:page) == 'home' %>
      <%= render 'layouts/navbar' %>
    <% #end %>

    <div class="container mb-auto">
      <%= yield %>
    </div>

    <footer class="mt-4">
      <div class="container-fluid">
        <p class="text-center text-muted">
          <span>Built with &hearts; by <a href="https://vinc.cc" class="text-muted"><strong>vinc</strong></a>.</span>
          <span>Code licensed <a href="https://github.com/vinc/news/blob/master/LICENSE" class="text-muted"><strong>MIT</strong></a>.</span>
        </p>
      <div>
    </footer>
  </body>
</html>